// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/Users/felipefr/opt/anaconda2/envs/tf115_env/inc
//                                  lude', '/Users/felipefr/opt/anaconda2/envs/tf115_e
//                                  nv/include/eigen3', '/Users/felipefr/opt/anaconda2
//                                  /envs/tf115_env/include']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0::ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0() : ufc::cell_integral()
{

}

ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0::~ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0()
{

}

const std::vector<bool> & ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0::enabled_coefficients() const
{
static const std::vector<bool> enabled({true});
return enabled;
}

void ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 0
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 0
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           0
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Quadrature rules
    alignas(32) static const double weights1[1] = { 0.5 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE10_C0_D01_Q1[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    double w0_d0_c0 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0_c0 += w[0][ic] * FE10_C0_D01_Q1[0][0][ic];
    const double J_c3 = coordinate_dofs[1] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE10_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE10_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE10_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE10_C0_D01_Q1[0][0][1];
    const double w0_d1_c0 = w[0][0] * FE10_C0_D01_Q1[0][0][0] + w[0][2] * FE10_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE10_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE10_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE10_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE10_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE10_C0_D01_Q1[0][0][1];
    alignas(32) double sp[13];
    sp[0] = J_c0 * J_c3;
    sp[1] = J_c1 * J_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = J_c3 / sp[2];
    sp[4] = w0_d0_c0 * sp[3];
    sp[5] = -1 * J_c2 / sp[2];
    sp[6] = w0_d1_c0 * sp[5];
    sp[7] = sp[4] + sp[6];
    sp[8] = J_c0 * J_c3;
    sp[9] = J_c1 * J_c2;
    sp[10] = sp[8] + -1 * sp[9];
    sp[11] = std::abs(sp[10]);
    sp[12] = sp[7] * sp[11];
    alignas(32) double BF0 = {};
    // Only 1 quadrature point, no loop
    {
        const double fw0 = sp[12] * weights1[0];
        BF0 += fw0;
    }
    A[0] = 0.0;
    A[0] += BF0;
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0()
{
  return new ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0();
}


ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::~ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main()
{
    // Do nothing
}

const char * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::signature() const
{
    return "d46fea5a4dbc5c8a97166ea7f49138f2cef80868a42ec817b7193acb12a19dd5eb6e2f5d7402cd245fce3d55294a4e6e4f12ae815fe0d817cbdacc2c934a7bc6";
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::rank() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::num_coefficients() const
{
    return 1;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 1)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0};
    return position[i];
}

ufc::finite_element * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_fe0a4aa76f67b05b91fd87e746f22ff05cc31ea4_finite_element_main();
}

ufc::dofmap * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_fe0a4aa76f67b05b91fd87e746f22ff05cc31ea4_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_093869bc26937bb34dc6ea89858ec40896423fd9_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_fe0a4aa76f67b05b91fd87e746f22ff05cc31ea4_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_fe0a4aa76f67b05b91fd87e746f22ff05cc31ea4_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_cell_subdomain_id() const
{
    return 1;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    switch (subdomain_id)
    {
    case 0:
        return create_ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_cell_integral_main_0();
    default:
        return nullptr;
    }
}

ufc::exterior_facet_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_cell_integral() const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main()
{
  return new ffc_form_197fdfbb79303987f5ad8837d9392a1bf40b2921_form_main();
}

